"""add_artwork_analytics_table

Revision ID: 0cc13612f78e
Revises: a76ba7fe1bc9
Create Date: 2026-06-11 01:58:38.058922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc13612f78e'
down_revision: Union[str, None] = 'a76ba7fe1bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
