"""add_instagram_publishing_fields

Revision ID: 61cbc473be4c
Revises: e04218e7bbac
Create Date: 2026-06-10 01:41:45.732630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61cbc473be4c'
down_revision: Union[str, None] = 'e04218e7bbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('instagram_status', sa.String(length=50), nullable=True))
    op.add_column('artworks', sa.Column('instagram_post_id', sa.String(length=500), nullable=True))
    op.add_column('artworks', sa.Column('instagram_permalink', sa.String(length=2000), nullable=True))
    op.add_column('artworks', sa.Column('instagram_published_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('artworks', 'reel_script',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artworks', 'reel_script',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('artworks', 'instagram_published_at')
    op.drop_column('artworks', 'instagram_permalink')
    op.drop_column('artworks', 'instagram_post_id')
    op.drop_column('artworks', 'instagram_status')
    # ### end Alembic commands ###
