"""add_youtube_publishing_fields

Revision ID: a76ba7fe1bc9
Revises: 61cbc473be4c
Create Date: 2026-06-10 03:09:59.877269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76ba7fe1bc9'
down_revision: Union[str, None] = '61cbc473be4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('youtube_status', sa.String(length=50), nullable=True))
    op.add_column('artworks', sa.Column('youtube_video_id', sa.String(length=100), nullable=True))
    op.add_column('artworks', sa.Column('youtube_url', sa.String(length=2000), nullable=True))
    op.add_column('artworks', sa.Column('youtube_published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'youtube_published_at')
    op.drop_column('artworks', 'youtube_url')
    op.drop_column('artworks', 'youtube_video_id')
    op.drop_column('artworks', 'youtube_status')
    # ### end Alembic commands ###
