"""Pydantic schemas for analytics API endpoints."""

from __future__ import annotations

import uuid
from datetime import datetime
from pydantic import BaseModel

from backend.schemas.artwork import ArtworkResponse


class ArtworkAnalyticsResponse(BaseModel):
    """Schema for individual analytics record representation."""

    id: uuid.UUID
    artwork_id: uuid.UUID
    platform: str
    views: int
    reach: int
    impressions: int
    likes: int
    comments: int
    shares: int
    saves: int
    watch_time: float
    engagement_rate: float
    collected_at: datetime
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class AIRecommendationResponse(BaseModel):
    """Schema for AI recommendations generated by Gemini."""

    best_posting_time: str
    best_platform: str
    best_hashtag_patterns: str
    best_artwork_category: str
    rationale: str


class PlatformMetrics(BaseModel):
    """Aggregated analytics metrics for a platform."""

    platform: str
    views: int
    likes: int
    comments: int
    shares: int
    saves: int
    watch_time: float
    engagement_rate: float


class DailyViewsItem(BaseModel):
    """Daily views chart metric data point."""

    date: str
    views: int
    platform: str


class DailyEngagementItem(BaseModel):
    """Daily engagement rate chart metric data point."""

    date: str
    engagement_rate: float
    platform: str


class DashboardAnalyticsResponse(BaseModel):
    """Response schema for overall dashboard analytics summary."""

    total_views: int
    total_likes: int
    total_comments: int
    total_reach: int
    total_impressions: int
    total_posts: int
    daily_views: list[DailyViewsItem]
    daily_engagement: list[DailyEngagementItem]
    platform_comparison: list[PlatformMetrics]
    ai_recommendations: AIRecommendationResponse | None = None


class TopPerformingReel(BaseModel):
    """Data summary for the top performing video reel."""

    artwork_id: uuid.UUID
    title: str | None
    reel_path: str | None
    views: int
    platform: str


class TopPerformingResponse(BaseModel):
    """Response schema for top performing media queries."""

    top_artwork: ArtworkResponse | None = None
    top_reel: TopPerformingReel | None = None
    top_hashtag: str | None = None
    top_platform: str | None = None
